Refactor Person to Client
AY2223S2-CS2103T-T09-4/tp pull request #59
Opened 2023-03-06 15:21 UTC by anunayajoshi

I have refactored Person to Client in the main and test files. Please do help to keep a look out if I have missed any.

2023-03-08 08:17 UTC, tituswe requested changes
Take note of DevGuide and UserGuide. Additional indentation was added, we need to check if it will mess up the CheckStyle

2023-03-08 08:17 UTC, tituswe commented on src/main/java/seedu/address/model/client/UniqueClientList.java
> +        return internalList.iterator();
Kindly add a test case to cover this

2023-03-08 08:17 UTC, tituswe commented on src/main/java/seedu/address/model/client/UniqueClientList.java
> +        return internalList.hashCode();
Kindly add a test case to cover this

2023-03-08 08:17 UTC, tituswe commented on src/main/java/seedu/address/ui/ClientCard.java
> +        this.client = client;
Kindly add a test case to cover this

2023-03-08 08:17 UTC, tituswe commented on src/main/java/seedu/address/ui/ClientCard.java
> +        client.getTags().stream()
Kindly add a test case to cover this

2023-03-08 08:17 UTC, tituswe commented on src/main/java/seedu/address/ui/ClientListPanel.java
> +    private final Logger logger = LogsCenter.getLogger(ClientListPanel.class);
Kindly add a test case to cover this

2023-03-08 08:17 UTC, tituswe commented on src/main/java/seedu/address/ui/ClientListPanel.java
> +    }
Kindly add a test case to cover this

2023-03-08 08:17 UTC, tituswe commented on src/main/java/seedu/address/ui/ClientListPanel.java
> +    class ClientListViewCell extends ListCell<Client> {
Kindly add a test case to cover this

2023-03-09 11:53 UTC, pangrwa reviewed
LGTM. Good effort in changing everything from `Person` to `Client`

2023-03-09 11:53 UTC, tituswe approved these changes
Do make sure to update the code cov next, otherwise keep up the good work! LGTM.

2023-03-09 11:53 UTC, merged